using Volo.Abp;

namespace InternshipManagementSystem.EntityFrameworkCore;

public abstract class InternshipManagementSystemEntityFrameworkCoreTestBase : InternshipManagementSystemTestBase<InternshipManagementSystemEntityFrameworkCoreTestModule>
{

}
