<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>InternshipManagementSystem</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InternshipManagementSystem.Domain\InternshipManagementSystem.Domain.csproj" />
    <ProjectReference Include="..\InternshipManagementSystem.Application.Contracts\InternshipManagementSystem.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.Account.Application" />
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Volo.Abp.Identity.Application" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" />
  </ItemGroup>

</Project>
