using InternshipManagementSystem.Samples;

namespace InternshipManagementSystem.EntityFrameworkCore.Applications;

//[Collection(InternshipManagementSystemTestConsts.CollectionDefinitionName)]
public class EfCoreSampleAppServiceTests : SampleAppServiceTests<InternshipManagementSystemEntityFrameworkCoreTestModule>
{
}